--custom tile map
local Map =
    {
        {
            {
                type="grass",
                depth=1
            },
            {
                type="ice",
                depth=1
            },
            {
                type=0,
                depth=1
            },
        },
        {
            {
                type="grass",
                depth=2
            },
            {
                type="ice",
                depth=2
            },
            {
                type=0,
                depth=2
            },
        },
        {
            {
                type="grass",
                depth=3
            },
            {
                type="ice",
                depth=3
            },
            {
                type="grass",
                depth=3
            },
        },
        {
            {
                type="grass",
                depth=1
            },
            {
                type="ice",
                depth=1
            },
            {
                type=0,
                depth=1
            },
        },
    }
return Map
