--custom tile map
local Map =
    {
        {
            {
                base="grass",
                depth=1
            },
            {
                base="ice",
                depth=1
            },
            {
                base=0,
                depth=1
            },
        },
        {
            {
                base="grass",
                depth=2
            },
            {
                base="ice",
                depth=2
            },
            {
                base=0,
                depth=2
            },
        },
        {
            {
                base="grass",
                depth=3
            },
            {
                base="ice",
                depth=3
            },
            {
                base="grass",
                depth=3
            },
        },
        {
            {
                base="grass",
                depth=1
            },
            {
                base="ice",
                depth=1
            },
            {
                base=0,
                depth=1
            },
        },
    }
return Map
